development:
  adapter: postgresql
  encoding: unicode
  database: Inventory_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Inventory_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Inventory_production
  pool: 5
  username:
  password:
